djeck1432/spotnet

frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dashboard/dashboard.css

Added tablet & mob adaptiveness to Dashboard page. Also, code optimization was performed for the dashboard page. 
Please, check it out and merge it if all is ok. Thank you.

Added tablet & mob adaptiveness to Dashboard page

---

frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dashboard/dashboard.css

Added adaptive improvements. Please merge it. Thank you.

added adaptive improvements

---

frontend/package.json
frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dashboard/dashboard.css

Styles' bug was fixed. Please check it and merge. Thank you.

Dashboard styles bug fix

---

frontend/src/components/LendingForm.js
frontend/src/pages/forms/Form.jsx
frontend/src/utils/contract.js

fix react env name

---

frontend/src/pages/forms/Form.jsx
frontend/src/pages/forms/form.css

Form styles changes are made. Please check it out and merge. Thank you.

Form styles changes

---

frontend/src/pages/spotnet/dashboard/Dashboard.jsx

dashboard-API-fixing

---

frontend/src/components/spinner/Spinner.jsx
frontend/src/components/spinner/spinner.css
frontend/src/pages/forms/Form.jsx
frontend/src/pages/forms/form.css

It was added spinner to Form page. Please check it out and merge once all is good. Thank you.

feat/added spinner to Form

---

web_app/api/serializers/dashboard.py
web_app/api/serializers/position.py
web_app/api/serializers/transaction.py

Resolves https://github.com/djeck1432/spotnet/issues/76

Update deprecated pydantic validator to field_validator

---

web_app/tests/test_dashboard.py

Fixes #79 
All 7 test cases are running

added a test_dashboard.py file in the tests folder

---

.env.dev
README.md
docker-compose.dev.yaml
docker-compose.yaml
requirements.txt
spotnet_tracker/celery_config.py
spotnet_tracker/tasks.py

1) Set up celery for the project
2) Updated `docker-compose.yaml` and `docker-compose.dev.yaml` with redis for celery
3) Created a simple task function to verify that all works as expected
4) Updated  `docker-compose.yaml` and `docker-compose.dev.yaml` files for start up celery workers
5) Update README.md about celery and how to run/stop/purge

Feat/add celery and redis  package to the project

---

web_app/tests/test_PositionDBConnector.py

Created test cases for PositionDBConnector

---

frontend/package.json
frontend/src/components/Dashboard/DashboardCard.jsx
frontend/src/components/Footer/Footer.jsx
frontend/src/components/Footer/footer.css
frontend/src/components/NavigationLinks.jsx
frontend/src/components/WalletSection.jsx
frontend/src/components/header/Header.jsx
frontend/src/components/header/header.css
frontend/src/hooks/useLockBodyScroll.js
frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dashboard/dashboard.css

Fixes #155 
https://github.com/user-attachments/assets/4d2ec3cd-f561-454f-a73d-d1afb18bc134

Added responsiveness to dashboard, header and footer

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/MultiplierSelector.jsx
frontend/src/components/multiplier.css
frontend/src/hooks/useMaxMultiplier.js
frontend/src/index.js
frontend/src/pages/forms/Form.jsx
frontend/src/pages/forms/form.css
frontend/src/utils/constants.js

added slider and reworked form

---

web_app/api/serializers/user.py
web_app/api/user.py

#194 Draft
@djeck1432 This is just a draft PR. The endpoint creation is still in progress.
I will update the `db/crud.py` too. I will re-run my pylint.

Implement endpoint for subscription

---

.github/workflows/cd.yml

This PR introduces a new cd.yml file to handle the deployment stage of the CD pipeline.
Key Features:
Installs SSH for secure connection.
Adds SSH key scanning for authentication.
Prepares the environment by setting up required files and variables.
Deploys the project to the specified server.
The current The pipeline setup is complete but has not been tested due to missing configuration details. Please ensure the following secrets are set up in the repository:
SERVER_USER: The username for SSH access.
SERVER_HOST: The IP address of the server.
SERVER_PORT: The SSH port of the server (default: 22).
SSH_PRIVATE_KEY: The private SSH key for server authentication.

Setup CD pipeline #238

---

frontend/src/App.jsx
frontend/src/components/Footer/Footer.jsx
frontend/src/components/Footer/footer.css
frontend/src/components/scrollButton/ScrollButton.css
frontend/src/components/scrollButton/ScrollButton.jsx
frontend/src/pages/spotnet/documentation/Documentation.jsx
frontend/src/pages/spotnet/documentation/Section.jsx
frontend/src/pages/spotnet/documentation/TableOfContents.jsx
frontend/src/pages/spotnet/documentation/documentation.css

Implementing the documentation page component for desktop version as requested in #222.
Changes include:
- Created documentation component for desktop view
Related to issue: #222

feat(FE): Implement Desktop Documentation Component

---

web_app/tests/test_vault.py

test: create test cases for vault endpoints

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/components/BalanceCards.jsx
frontend/src/components/LendingForm.js
frontend/src/components/Telegram/TelegramLogin.jsx
frontend/src/components/TelegramNotificationModal/TelegramNotificationModal.jsx
frontend/src/components/WalletSection.jsx
frontend/src/components/header/Header.jsx
frontend/src/hooks/useClosePosition.js
frontend/src/hooks/useDashboardData.js
frontend/src/pages/forms/Form.jsx
frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dont_miss/DontMiss.jsx
frontend/src/pages/spotnet/home/Home.jsx
frontend/src/pages/spotnet/spotnet_app/SpotnetApp.js
frontend/src/stores/useWalletStore.js

Changes Made  are 
Global Store Creation
Added a new global store using Zustand (useWalletStore) to manage walletId and setWalletId actions.
Ensured the store initializes walletId from localStorage and synchronizes updates to localStorage.
Code Refactoring
Replaced prop drilling of walletId with direct access to the global store.
Update all affected components and hooks, including useDashboardData, to utilize the global store.

Create global store for walledId and added them to the necessary page

---

spotnet_tracker/tasks.py
web_app/contract_tools/mixins/alert.py
web_app/db/crud/telegram.py

feat: background-task-health-check

---

frontend/src/pages/spotnet/dashboard/Dashboard.jsx
frontend/src/pages/spotnet/dashboard/dashboard.css

048cd4286255bb58b3617992b4d3160290b441e7 :
- tiny formatting adjustment one some lines
- started working on @media (max-width: 425px)
- made changes to the width to fix display bug
048cd4286255bb58b3617992b4d3160290b441e7 :
- Modification of some class name to better reflect role and avoid further overriding with other components
- Should I fix and tweak the display any further ?
- If yes, should I do it for both different media size displays ?

Fix dashboard mobile layout

---

frontend/src/components/MultiplierSelector.jsx
frontend/src/components/multiplier.css
frontend/src/pages/forms/Form.jsx

ece3b0f11947cb26aa7b4864e3191fd7782398f4 : 
- Slider moving from 0.1 by 0.1
- Precise current multiplier displayed above cursor

Rework slider on a Form page

---

frontend/src/components/header/header.css
frontend/src/components/mobDropdownMenu/mobDropdownMenu.css

fix: header popups

---

frontend/src/components/MetricCard/metricCard.css
frontend/src/pages/vault/vaultLayout.css
frontend/src/pages/vault/withdraw/withdraw.css

fixes #295
Made withdraw vault page responsive on mobile screens.

feat: make vault withdraw page mobile resp.

---

manual_test_scenarios.md

Documented the process for manual testing

test: Create scenario for manual testing

---

web_app/api/telegram.py
web_app/telegram/utils.py

Refactor Telegram webhook handling and response generation
- Introduced a new method `build_multipart_response` to create multipart responses for Telegram webhooks.
- Updated `telegram_webhook` to utilize the new response generation method and added error logging.
- Refactored `generate_multipart_telegram_response` to yield multipart form-data chunks, improving response handling.
- Enhanced imports for better organization and clarity.

Telegram fix webhook response

---

web_app/contract_tools/mixins/alert.py
web_app/db/crud/telegram.py
web_app/telegram/handlers/command.py

1. fix logic in telegram
2. test alert message

rework telegram logic

---

web_app/tests/test_deposit_mixin.py

fix test cases for deposit_mixin

fix test cases

---

frontend/src/hooks/useHealthRatio.js
frontend/src/pages/forms/Form.jsx
frontend/src/pages/forms/form.css

added the calculation for health factor on the dashboard page

---

frontend/src/App.jsx
frontend/src/services/telegram.js
web_app/telegram/handlers/command.py

Changes how we handle Telegram user info. 
1. **Removed Unused State**: I got rid of the `tgUser` state since we don’t need it anymore.
2. **Simplified Wallet ID Fetching**: Now, we directly use the Telegram Web App data to get the wallet ID.
3. **Better Error Handling**: If there’s an error while getting the wallet ID, we show a notification to the user.
4. **Cleaned Up Code**: I removed some unnecessary local storage stuff related to `tgUser`.
These changes should make the web page work better in Telegram mini apps!

[Frontend] Refactor Telegram User Handling in App Component

---

web_app/contract_tools/blockchain_call.py

Added the fetch_portfolio to StarkClient that fetches all available token balances from the smart contract. Here the smart contract address is sent to the function as a parameter. a test __init__ is written below the file.

feat: added fetch_portfolio

---

frontend/src/App.jsx
frontend/src/pages/documentation/Documentation.jsx
frontend/src/pages/spotnet/defi-spring/DefiSpring.jsx
frontend/src/pages/terms-and-conditions/TermsAndConditions.jsx
frontend/src/pages/terms-and-conditions/terms-and-conditions.css

Imrove previous section: Getting start:Setting Up Wallet
Added information in introduction and overview by removing square brackets, to see full view of picture in Documentation page at footer. 
Any comments and changes will be taken into account, thank you.

Spotnet documentation changes, small fixes in typo errors

---

frontend/.eslintrc.json
frontend/src/App.jsx
frontend/src/components/layout/navigation-links/NavigationLinks.jsx
frontend/src/components/ui/token-selector/TokenSelector.jsx
frontend/src/components/ui/token-selector/tokenSelector.css
frontend/src/hooks/useAddDeposit.js
frontend/src/pages/add-deposit/AddDeposit.jsx
frontend/src/pages/add-deposit/addDeposit.css
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/form/Form.jsx
frontend/src/pages/form/form.css
frontend/src/utils/regex.js

wip: deposit page

---

frontend/src/services/transaction.js
frontend/test/services/transaction.test.js
web_app/api/position.py
web_app/db/crud/__init__.py
web_app/db/crud/transaction.py
web_app/tests/test_positions.py

feat: implement save transaction data for closed position

---

frontend/package-lock.json
frontend/src/hooks/useClosePosition.js
frontend/yarn.lock
package-lock.json
web_app/api/position.py
web_app/tests/test_positions.py

[Backend] Save transaction data for closed position

---

frontend/public/index.html
frontend/src/hooks/useClosePosition.js
frontend/src/services/contract.js
frontend/src/services/transaction.js
frontend/src/services/wallet.js

Refactor wallet connection logic and update API calls
- Replaced direct wallet connection calls with a `getWallet` function.
- Updated API calls in `useClosePosition` to use query parameters instead of string interpolation.
- Commented out the get-starknet.js script in `index.html`.

[Frontend] Fix connect logic

---

docker-compose.back.yaml
frontend/src/hooks/useAddDeposit.js
frontend/src/pages/add-deposit/AddDeposit.jsx
frontend/src/services/transaction.js
web_app/alembic/versions/8a132b70dc8b_add_extra_deposit_status_tx.py
web_app/api/position.py
web_app/api/serializers/position.py
web_app/db/crud/position.py
web_app/db/models.py
web_app/tests/conftest.py
web_app/tests/test_positions.py

Refactor deposit handling and enhance backend API for extra deposits
- Fix `docker-compose.back.yaml` command syntax.
- Refactored `useAddDeposit` hook to include wallet retrieval and transaction handling for extra deposits.
- Enhanced `AddDeposit` component to utilize dashboard data for position ID.
- Implemented new API endpoint(get|post) `/api/add-extra-deposit/{position_id}` to prepare and process extra deposit requests.
- Updated serializers and database models to accommodate new deposit data structure and transaction status.

Fix extra(add) deposit

---

frontend/Dockerfile.dev
frontend/src/services/wallet.js
frontend/test/services/contract.test.js
frontend/test/services/transaction.test.js
frontend/test/services/wallet.test.js

fix the frontend tests error

---

web_app/api/serializers/user.py
web_app/api/user.py
web_app/tests/test_user.py

* [`web_app/api/serializers/user.py`](diffhunk://#diff-840808a3cece778520c8d90f01942da6e252240948014dcbe71229b5c2b677bcR104-R127): Added `BugReportRequest` and `BugReportResponse` models to handle bug report submissions and responses.
* [`web_app/api/user.py`](diffhunk://#diff-603b7d68b119168a3676b70d01b6630176cc0f0467b52d5939730c1869914ae5R263-R321): Implemented the `save_bug_report` endpoint to receive bug reports, validate them, and send them to Sentry for tracking.
* [`web_app/tests/test_user.py`](diffhunk://#diff-e770c67a8e3a8fb06f293235a717b8b4f0057ba4097620d5b48af1dfbcdb4c1aR352-R439): Added tests for the `save_bug_report` endpoint to ensure successful submissions and validation failures.
Closes #481

feat: add bug report API with validation and Sentry integration

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/integration-tests.yml
Makefile
README.md
devops/docker-compose.back.yaml
devops/docker-compose.dev-windows.yaml
devops/docker-compose.dev.yaml
devops/docker-compose.yaml

Refactored the docker compose files and place them in a separate directory.
- Updated the required paths in relevant files.
- Updated the readme to match change.
-  Updated the make file.
Fixes #483

Fix: Update files structure for docker compose

---

.gitignore
frontend/package.json
frontend/src/components/home/home/home.css
frontend/src/globals.css
frontend/src/pages/DashboardLayout.css
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/dashboard/dashboard.css
frontend/src/pages/withdraw/withdraw.css
frontend/src/utils/cn.js
frontend/tailwind.config.js
frontend/vite.config.mjs
frontend/yarn.lock

Setup Tailwind CSS in the Project

---

frontend/src/hooks/usePositionHistory.js
frontend/src/pages/position-history/PositionHistory.jsx
frontend/src/pages/position-history/PositionPagination.jsx

@djeck1432 Sorry for the delay.

refac : updated pagination

---

frontend/src/App.jsx
frontend/src/pages/leaderboard/Leaderboard.jsx

Created a leaderboard page #536

feat:create leaderboard page

---

margin_app/app/alembic/env.py
margin_app/app/models/__init__.py
margin_app/app/models/pool.py

#573
created pool.py and made Pool and UserPool classes

created pool.py and made Pool and UserPool classes

---

margin_app/app/crud/deposit.py
margin_app/app/crud/user.py

Add: crud for user

---

margin_app/app/api/pools.py
margin_app/app/crud/pool.py
margin_app/app/main.py
margin_app/app/schemas/pools.py

Add endpoint create_user_pool

---

margin_app/app/api/pools.py
margin_app/app/schemas/pools.py

Added update_user_pool endpoint

added endpoint update_user_pool

---

margin_app/app/api/user.py
margin_app/app/main.py
margin_app/app/schemas/user.py

Close: #639 
- Add `add_user_deposit` API endpoint

feat: add add_user_deposit API endpoint

---

margin_app/app/api/deposit.py
margin_app/app/main.py
margin_app/app/schemas/deposit.py
margin_app/app/schemas/pools.py

Add update deposit endpoint

---

margin_app/app/tests/test_pools_crud.py

fixing issues with async and pylint

test for userpool and pool crud

---

margin_app/app/tests/api/liquidation.py

#677 
1. Created new `liquidation.py` file at `margin_app/app/tests/api`
2. Added negative and positive test cases.

test cases for liquidation process added

---

margin_app/app/api/pools.py
margin_app/app/crud/base.py
margin_app/app/crud/pool.py
margin_app/app/tests/api/test_pool_api.py
margin_app/app/tests/test_db_connector.py
margin_app/app/tests/test_pools_crud.py
margin_app/docker-compose.yml

closes #727 
- Added a ```get_all_pools``` endpoint and implemented a relevant crud method.
- Added required ```get_objects``` method to ```DBConnector``` class.
- Covered implemented logic with tests.

feat [Margin App] Add get_all_pools Endpoint

---

margin_app/app/api/admin.py
margin_app/app/schemas/admin.py

Created schemas: AdminRequest and AdminResponse.
Created api methods: for add admin and get admin by id

created admin api: add and get methods.

---

margin_app/app/utils/constants.py

Added an `EventName` enum class in `margin_app/app/utils/constants.py` to standardize transaction event types in the margin trading system.
- ✅ Well-structured enum implementation using Python's standard `Enum` class
- ✅ Clear and descriptive enum values that match their string representations
- ✅ Comprehensive docstring with:
- Class-level description
- Purpose explanation
- Detailed attribute documentation
- ✅ Follows Python naming conventions (snake_case for enum values)
- ✅ Values are self-documenting and consistent with their usage
The implementation includes all required transaction events:
- `open_position`: For new trading position events
- `close_position`: For closing existing positions
- `create_pool`: For new liquidity pool creation
- `close_pool`: For closing existing pools
- …

feat: add EventName enum for transaction events

---

margin_frontend/src/routeTree.gen.ts
margin_frontend/src/routes/change-password.tsx
margin_frontend/src/ui/views/ResetPasswordForm.tsx

feat for [[Margin app] Add new component change password #722](https://github.com/djeck1432/spotnet/issues/722)
A new route and a component that reuses the app UI components. No actions on the form because there is no API.
Request review:
@djeck1432 
@CBoYXD

Add new component change password

---

margin_app/app/api/margin_position.py
margin_app/app/crud/margin_position.py
margin_app/app/models/__init__.py
margin_app/app/models/margin_position.py

Created get_all_margin_positions api endpoint;
created get_all_margin_positions method in margin_position crud;
fixed small problems in linter.

created get_all_margin_positions endpoint #732

---

margin_app/app/api/user.py
margin_app/app/schemas/user.py
margin_app/app/tests/api/test_user_api.py

feat: [[Margin app] Fix /add_user_deposit #773](https://github.com/djeck1432/spotnet/issues/773)
Review request:
@djeck1432

remove duplicate. upd response

---

margin_app/app/api/pools.py
margin_app/app/crud/pool.py

Closes #726 
- created a new get_all_user_pools enpoint
- created a method for retrieving all user pools from the database

[Margin app] Add get_all_user_pools endpoint

---

margin_app/app/api/admin.py
margin_app/app/main.py
margin_app/app/services/auth.py
margin_app/app/tests/api/test_admin_api.py
margin_app/app/tests/test_auth_admin_user_middleware.py

Closes #764 
- Add `auth_admin_user` middleware

feat [Margin App]: Add `auth_admin_user` middleware

---

margin_app/app/api/margin_position.py
margin_app/app/tests/api/test_margin_position_api.py

Add get_margin_by_id and tests for it

---

margin_app/app/api/admin.py
margin_app/app/api/margin_position.py
margin_app/app/api/pools.py
margin_app/app/api/user.py

Remove all unnecessary db parameters in endpoints

[Margin app] Remove the unnecessary db parameter in endpoints where it is not used.

---

.github/workflows/cd.yml
margin_app/app/api/fix_endpoints.py

sorry this took long ...the issue can be found in spotnet\margin_app\app\api\fix_endpoints. fix_endpoints was the task i worked on

[Margin app] Standardize /all endpoints #771 

---

margin_app/app/api/auth.py
margin_app/app/api/deposit.py
margin_app/app/tests/api/test_deposit_api.py

Add get_deposit_by_id and tests for it

---

margin/margin_app/app/core/config.py
margin/margin_app/app/db/seed_data.py
margin/margin_app/app/db/sessions.py
margin/margin_app/app/models/__init__.py

Added and tested generate_transaction func.

add generate_transaction func

---

README.md
devops/docker-compose.margin.back.yml
margin/margin_frontend/.dockerignore
margin/margin_frontend/Dockerfile

Dockerized frontend application

---

.github/workflows/margin_app_ci.yml

Fixed margin_app_ci workflow

---

margin/margin_app/app/api/pools.py
margin/margin_app/app/crud/pool.py
margin/margin_app/app/tests/test_pools_crud.py

implements endpoint for getting user pool by id
close #869 
- added new endpoint in `app/api/pools.py`
- added helper  in `app/crud/pool.py`
- added tests in `test_pools_crud.py`
- all previous and new tests passed

feat: implements endpoint for getting user pool by id

---

margin/margin_app/app/api/admin.py
margin/margin_app/app/tests/api/test_admin_api.py
margin/margin_app/app/tests/api/test_google_auth.py
margin/margin_app/app/tests/api/test_user_auth_api.py
margin/margin_app/app/tests/test_auth_admin_user_middleware.py

This PR:
- updates the admin user middleware test cases
- removes duplicate update admin name endpoint definitions
close #904

tests(margin_app): fixed admin user middleware auth tests

---

margin/margin_app/app/api/auth.py
margin/margin_app/app/schemas/admin.py
margin/margin_app/app/tests/api/test_auth.py

fix reset_password
