web_app/alembic/env.py
web_app/api/main.py

Delete call function `Base.metadata.create_all(bind=engine).`

Fix outside migration create tables

---

frontend/test/constants.js

Changed the backend url due to previous typo error

fix: changed backend url typo error

---

web_app/api/serializers/airdrop.py
web_app/contract_tools/airdrop.py
web_app/tests/test_zklend_airdrop.py

hello @djeck1432 kindly review :) #141

test: add test for airdrop.py

---

frontend/package-lock.json
frontend/src/components/StarMaker.jsx
frontend/src/pages/spotnet/information/Informaion.jsx
frontend/src/pages/spotnet/information/Information.jsx
frontend/src/pages/spotnet/spotnet_app/SpotnetApp.js

Fetch data from /api/get_stats and display in frontend

---

poetry.lock
pyproject.toml
web_app/db/README.md
web_app/db/seed_data.py

Created script to populate db with dummy data

Create script to populate with fake data db

---

web_app/api/user.py
web_app/contract_tools/mixins/dashboard.py
web_app/db/crud.py

Calculated TVL amount

---

web_app/contract_tools/mixins/alert.py
web_app/contract_tools/mixins/custom_exception.py
web_app/db/crud.py

cloese issue [#199]
This PR implements the `AlertMixin` class and its associated functionality to check the health ratio level of users with an OPENED position status. If a user's health ratio level is lower than the required threshold of `1.1`, a custom exception `HealthRatioLevelLowException` is raised. The following changes are included:
- **AlertMixin Class**: Added the `check_users_health_ratio_level` method, which:
- Fetches all users with an OPENED position.
- Retrieves the user's position using `DashboardMixin`.
- Checks the user's health ratio level, raising the `HealthRatioLevelLowException` if the ratio is below `1.1`.
- **UserDBConnector Class**: Added the `get_all_users_with_opened_position` method, which fetches all users with an OPENED position status from the database.
- …

feat: implement function to check health_ratio_level per wallet_id 

---

web_app/api/user.py
web_app/db/crud.py

- Added new GET endpoint `/api/has-user-opened-position` to check user's position status
- Implemented CRUD method `has_opened_position` in PositionDBConnector
- Added boolean response for position status check
- New endpoint accepts `wallet_id` as input parameter
- Returns simple boolean response: `true` if user has opened position, `false` otherwise
- Implements proper error handling for database queries
Closes #210

feat: create endpoint to check if user has already opened position 

---

web_app/tests/db/deposit_db_tests.py

Test DepositDBConnector

---

frontend/test/services/wallet.test.js

I like cherry.
TG: @mymiracle0118
I have fixed test cases on FE.
The comparison value for USDC in the unit test using jest was set incorrectly.
I re-set it considering that the decimal of USDC is 6.
I would appreciate it if you could confirm that it has been resolved.

fix test cases on FE

---

web_app/api/position.py
web_app/api/serializers/position.py
web_app/tests/test_positions.py

- Add GET `/api/user-positions/{wallet_id}` endpoint to fetch all positions for a user
- Create response models `UserPositionResponse` and `UserPositionsListResponse`
- Implement `get_positions_by_wallet_id` in PositionDBConnector
- Add test cases for success and error scenarios
- Added unit tests for:
- Successful position retrieval
- Empty wallet ID handling
- No positions case
- Invalid wallet ID case
Related Issues
Closes #351

Add user positions endpoint with tests

---

zklend_airdrop_proof_research.md

This PR includes documentation and implementation related to retrieving airdrop proofs for the specified ZkLend contract. It outlines the research process, tested endpoints, and findings. closes #354 
1. The research involved testing the ZkLend API and several alternative endpoints to retrieve airdrop proof data for the contract `0x698b63df00be56ba39447c9b9ca576ffd0edba0526d98b3e8e4a902ffcf12f0`.
2. All tested endpoints failed to return valid data for the given address, including the ZkLend API (`https://app.zklend.com/api/reward/all/`).
3. The document provides insights into the failed attempts, logs, and structured code for future reference.

Document research and implementation for retrieving ZkLend airdrop proofs for the specified contract.

---

web_app/api/user.py
web_app/contract_tools/blockchain_call.py

add withdraw all contract

---

web_app/api/dashboard.py
web_app/api/position.py
web_app/db/crud/position.py
web_app/test_integration/test_close_position.py
web_app/tests/db/test_PositionDBConnector.py

Changes include:
- Constant of PAGINATION_STEP is added with the value of 10
- `get_user_positions` function endpoint now has an optional `start` argument for accepting query parameter of `start`
- `get_positions_by_wallet_id` db function now accepts `start`, and `limit` parameters to accommodate the change
No breaking changes
Modification to a functionality is done and was to be expected due to the nature of issue.

Feat: Add pagination to position history endpoint

---

frontend/jest.config.js
frontend/package.json
frontend/src/services/contract.js
frontend/src/services/transaction.js
frontend/src/services/wallet.js
frontend/test/services/contract.test.js
frontend/test/services/transaction.test.js
frontend/test/services/wallet.test.js

updates for frontend wallet connection 

---

.github/workflows/cairo_tests.yml
.github/workflows/ci.yml
.github/workflows/frontend_tests.yml
.github/workflows/integration-tests.yml
.github/workflows/pylint.yml
README.md
frontend/src/components/dashboard/deposited/Deposited.jsx
frontend/src/pages/dashboard/Dashboard.jsx
scripts/migrate.sh
web_app/api/dashboard.py
web_app/contract_tools/mixins/dashboard.py
web_app/tests/test_dashboard.py

Update dashboard data fetching to include extra deposited token amounts, create state depositData.
Clear def get_position_balance to return only position balance.

[Backend] Display user extra deposit

---

.github/workflows/integration-tests.yml
web_app/db/crud/position.py
web_app/test_integration/test_close_position.py
web_app/test_integration/test_create_position.py
web_app/test_integration/test_extra_deposit.py
web_app/test_integration/test_liquidate_position.py
web_app/test_integration/utils.py

Fixes:
- Updates the checkout action in the integration tests workflow to v4.
- Modifies the return type annotation for `get_positions_by_wallet_id` in `PositionDBConnector` to `list[dict]`.
- Adds a method to delete all extra deposits for a position.
- Implements integration tests for position creation, closing, liquidation, and extra deposits.
- Adds a utility function for creating temporary users for testing.
This PR introduces integration tests for key functionalities: position creation, closing, liquidation, and extra deposits. It also includes a utility function for creating temporary users to ensure tests are isolated and do not interfere with each other. Additionally, a method to delete all extra deposits for a position was added.

Update integration tests add test by new flieds or refactory

---

frontend/src/assets/icons/form-icon.svg
frontend/src/components/layout/navigation-links/NavigationLinks.jsx
frontend/src/components/ui/token-selector/TokenSelector.jsx
frontend/src/pages/DashboardLayout.jsx

This PR updates the UI by implementing the following changes:  
✅ Moved `kSTRK` token to the form page.  
✅ Removed it from the header and relocated it to the dashboard under "Open Position."  
✅ Renamed "Add Deposit" to "Add Extra Deposit."  
✅ Ensured dashboard subpages follow the new layout structure.  
- Updated component structure to reflect the new placement.  
- Modified styles and routes where necessary.  
- Adjusted labels for better clarity.  
Closes #560

feat:improved user's experience

---

margin_app/app/alembic/env.py
margin_app/app/core/config.py
margin_app/app/main.py
margin_app/app/models/__init__.py
margin_app/app/models/base.py
margin_app/app/models/user.py

Closes #566
a new model  in the `app/models/user.py` file:
the `User` model with `wallet_id`, `deposit`, and `margin_position` attributes, and set up one-to-many relationships with the `Deposit` and `MarginPosition`.

[MarginApp] Add new User model 

---

margin_app/app/models/__init__.py
margin_app/app/models/liquidation.py

To Close: #569
Added Liquidation Model to the margin app

feat: added liquidation model

---

margin_app/app/tests/margin_position_crud.py

Closes #624
Adds unit tests for the `MarginPositionCRUD` class, covering both positive and negative scenarios. 
* [`margin_app/app/tests/margin_position_crud.py`](diffhunk://#diff-861bebd78810e59bf31330bf846655e0f69bb8697cd856efee0cb681409c7f82R1-R182): Added fixtures for `MarginPositionCRUD` ,positive and negative test cases

[Margin app] Add test cases for MarginPosition 

---

margin_app/app/tests/api/user.py

closes #676 
I added the ` pylint: disable=redefined-outer-name` to avoid pylint warning concerning defining from outer scope

[Margin app]: Add test cases for user endpoints

---

margin_app/app/alembic/versions/2025-03-07_new_order_model.py
margin_app/app/api/order.py
margin_app/app/crud/order.py
margin_app/app/main.py
margin_app/app/models/order.py
margin_app/app/schemas/order.py
margin_app/app/tests/api/order.py
margin_app/app/tests/test_order_crud.py

Closes #702 
a new order management system to the `margin_app` application. 
* Created a new migration for order model . (`margin_app/app/alembic/versions/2025-03-07_new_order_model.py`)
* Added CRUD operations for the `Order` model in `margin_app/app/crud/order.py`.
* Implemented API endpoints for creating orders in `margin_app/app/api/order.py`.
* Included the new `order` API router in the main application entry point in `margin_app/app/main.py`.
** Defined Pydantic schemas for order creation and response in `margin_app/app/schemas/order.py`.
** Added unit tests for the `Order` API endpoints in `margin_app/app/tests/api/order.py`.
** Added unit tests for the `OrderCRUD` class in `margin_app/app/tests/test_order_crud.py`.

[Margin App] Add logic for Order model

---

margin/margin_app/app/api/auth.py
margin/margin_app/app/core/config.py
margin/margin_app/app/schemas/auth.py
margin/margin_app/app/services/auth/base.py
margin/margin_app/app/tests/services/test_auth_services.py

- Implemented a new endpoint for user signup confirmation that handles JWT token validation and user creation.
- Added a `decode_signup_token` function to extract email from the JWT token, with error handling for invalid and expired tokens.
- Introduced a `SignupConfirmation` schema for request validation.
- Updated tests to cover the new functionality for decoding signup tokens.
closes- #875

feat: Add signup confirmation endpoint and decode signup token functionality

---

margin/margin_app/app/crud/admin.py
margin/margin_app/app/models/admin.py
margin/margin_app/app/schemas/admin.py
package-lock.json

- Updated the Admin database model to make the `name` field optional.
- Updated Pydantic schema for admin creation to accept `name` as optional.
- Refactored the `/admin/add` endpoint to allow admin creation with only an email or with both email and name.
- Updated CRUD logic to handle the optional name field.
- Added/updated tests to cover:
- Creating an admin with only an email.
- Creating an admin with both email and name.
- Handling invalid email input.
This PR addresses issue #877 and improves flexibility for admin creation, as well as test coverage for the endpoint.
close #877

 Refactor: Make Admin Name Optional and Update /admin/add Endpoint

---

margin/margin_frontend/src/ui/admin/dashboard/AccountValuesCard.tsx
margin/margin_frontend/src/ui/admin/dashboard/DashboardStats.tsx
margin/margin_frontend/src/ui/admin/dashboard/dashboardMain.tsx

Closes #868 
This PR implements the **admin dashboard** page in the frontend, following the issue guidelines:
- **Route:** `/admin/dashboard`
- **Mock data** for:
- Users
- Opened positions
- Liquidated positions
- Opened orders
- **Visual design** based on the provided example image.
- **Reusable components** and clean structure, all within `margin_frontend` (not in `admin_template`).
- **New visual component:** `AccountValuesCard` replicates the account values card design (Net Value, Coins value, Cash Balance) with icons and professional formatting.
- **Dashboard integration:** Everything is integrated into the `/admin/dashboard` page using the existing admin layout.
- **Mocked data:** No backend connection yet; all data is static for now.
You can view the page at: …

feat(admin-dashboard): add admin dashboard stats cards with mock data

---

margin/margin_app/app/api/admin.py
margin/margin_app/app/main.py
margin/margin_app/app/schemas/admin.py
margin/margin_app/app/services/auth/base.py
margin/margin_app/app/services/emails.py
margin/margin_app/app/tests/api/test_admin_api.py

This PR:
- updates `reset_password` endpoint to accept only `new_password` parameter
- implements jwt token verification with email extraction
- adds password reset endpoints to middleware exclusions in `main.py`
- adds comprehensive test cases for password reset
close #916

fix: admin reset password logic
